#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

security:
  users:
    Obiwan:
      password: yodarulez
      roles: SEED.JEDI
    Anakin:
      password: imsodark
      roles: SEED.PADAWAN
  roles:
    padawan: [SEED.PADAWAN, FND.ETUDES]
    jedi: SEED.JEDI
  permissions:
    jedi: ['lightSaber:*', 'academy:*']
    padawan: 'academy:learn'
audit:
  writers: org.seedstack.audit.internal.ConsoleTrailWriter
